# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: install  npm
          command: npm run lint
  test:
    docker:
      - image: circleci/node:13.8.0
      steps:
      - checkout
      - run:
          name: test npm
          command: npm run test
  analyse:
    docker:
      - image: circleci/node:13.8.0
      steps:
      - checkout
      - run:
          name: audit npm
          command: npm run audit
  

workflows:
  ci_pipeline:
    jobs:
      - build
      - test:
          requires:
                - build
      - analyse
          requires:
                - test

